/*
-- Query: SELECT * FROM innodb.SERVICIOS
LIMIT 0, 1000

-- Date: 2020-05-06 22:05
*/
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('19','2 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('19','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('19','Tv por cable');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('20','3 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('20','intenet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('20','Tv por cable');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('21','2 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('21','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('21','piscina');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('22','1 cuarto y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('22','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('22','parking');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('23','2 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('23','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('23','tv por cable');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('24','3 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('24','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('24','parking');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('24','tv por cable');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('25','2 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('25','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('25','parking');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('26','3 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('26','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('26','parking');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('27','3 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('27','parking');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('27','piscina');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('28','4 cuartos y 3 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('28','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('28','parking');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('29','3 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('29','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('29','piscina');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('30','1 cuarto y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('30','aire acondicionado');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('30','tv por cable');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('31','3 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('31','parking');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('31','piscina');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('32','3 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('32','parking');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('32','piscina');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('33','3 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('33','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('33','parking');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('34','3 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('34','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('34','piscina');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('35','3 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('35','piscina');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('35','tv por cable');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('36','3 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('36','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('36','tv por cable');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('37','3 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('37','cocina integrada');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('37','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('37','parqueadero');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('38','2 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('38','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('38','tv');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('39','2 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('39','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('40','3 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('40','cocina integrada');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('40','parqueadero');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('41','1 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('41','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('41','parqueadero');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('41','tv');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('42','3 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('42','cocina integrada');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('42','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('43','parqueadero');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('44','2 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('44','cocina integrada');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('44','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('45','1 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('45','cocina integrada');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('46','1 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('46','parqueadero');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('47','3 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('47','cocina integrada');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('47','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('47','parqueadero');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('48','4 cuartos y 3 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('48','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('48','parqueadero');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('48','piscina');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('48','tv');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('49','2 cuartos y 3 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('49','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('49','parqueadero');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('50','3 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('50','cocina integrada');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('50','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('50','tv');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('51','2 cuartos y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('51','4 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('51','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('52','cocina integrada');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('52','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('52','piscina');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('52','tv');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('53','3 cuartos y 2 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('53','cocina integrada');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('53','parqueadero');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('54','1 cuarto y 1 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('54','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('55','3 cuartos y 3 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('55','cocina integrada');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('55','internet');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('55','piscina');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('55','tv');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('56','3 cuartos y 3 wc');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('56','cocina integrada');
INSERT INTO `` (`idPropiedad`,`nombreServicio`) VALUES ('56','tv');
