/*
-- Query: SELECT * FROM innodb.PROPIEDAD WHERE idCiudad = 5 OR idCiudad=6 OR idCiudad= 7
LIMIT 0, 1000


*/
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('19','5','Manga','1','Apartamento juan','Gran espacio para pasar el tiempo en cartagena.',3.5,'Cra 8 nro 1',25000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/581-2819/581-2819_1_p.jpg','Juan Esteban Osorio');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('20','5','Boca Grand','1','Apartamento en Boca Grande','Mejor estadia en Cartagena de Indias.',4,'Cra 9 nro 2',65000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/3967-1019051/3967-1019051_20_p.jpg','Pablo Martinez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('21','5','Pie de la','1','Apartamento pie de popa','Noches innolvidables en esta propiedad.',5,'Cra 80 nro 13',57000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/2398-21929/2398-21929_1_p.jpg','Camilo Serna');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('22','5','Marbella','1','Apartamento en Marbella','Gran apartamento en marbella',4,'Cra 9 nro 29',45000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/3967-2474895/3967-2474895_1_p.jpg','Alma Marcela Lopez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('23','5','Castillogr','1','Apartamento de Castillogrande','Ubicado en uno de los mejores barrios de la heroica.',3,'Cra 2 nro 02',87000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/2398-21780/2398-21780_1_p.jpg','Larry Dominguez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('24','5','Manga','1','Manga apartament','Grandes espacios en este apartamento',5,'Cra 5 nro 1',32000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/3967-1984797/3967-1984797_1_p.jpg','Esteban Galindo');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('25','7','Costa herm','1','Casa en Costa hermosa','Gran comodidad en costa hermosa soledad',4,'Calle 2 nro 2',82000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/130-3323/130-3323_1_p.jpg','Daniel Rios');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('26','7','Hipodromo','1','apto en Hipodromo','El mejor lugar para estar en soledad',4.5,'Calle 29 nro 29',45000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/671-70177/671-70177_19_p.jpg','Juan Camilo Gil');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('27','7','Las trinit','1','Apto en Las trinitarias','Apto con grandes espacios para vivir tranquilo',5,'Calle 2 nro 7',56000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/5410-9898/5410-9898_1_p.jpg','Hermen Taborda');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('28','7','Trinitaria','1','Apartamento en Trinitarias','Ubicado en el mejor sector de soledad',4,'Calle 24 nro 1',15000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/671-70188/671-70188_21_p.jpg','Sebastian Lopoldo');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('29','7','Villa kata','1','Apto En villa katanga','Mejor estadia en villa katanga',3.5,'Calle 20 nro 29',45000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/671-74199/671-74199_9_p.jpg','Pedro Pablo L');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('30','7','El parque','1','Apto en Parque','Gran apto ubicado en el barrio Parque',4,'Calle 5 nro 29',100000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/130-2777/130-2777_21_p.jpg','Luis Fernanda W');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('31','6','Avenida de','1','Apto en renta avenida del rio','Gran apartamento en zona residencial cucuta',4,'Cra 20 nro 2',45000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/386-2745/386-2745_18_p.jpg','Roberto Florez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('32','6','Blanco','1','Apto en Blanco','Una de las mejores ubicaciones en cucuta',3.5,'Cra 21 nro 28',29000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/386-2051/386-2051_1_p.jpg','Aldrin Alexander R');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('33','6','Prados del','1','Apartamento en prados del norte','Gran lugar para pasar estadia en cucuta',4,'Cra 30 nro 11',32000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/386-8119/386-8119_1_p.jpg','Pacho Maturana');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('34','6','Villa del','1','Apto en villa del rosario','Ubicado en una buena zona residencial',4.5,'Cra 27 nro 43',50000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/386-8193/386-8193_1_p.jpg','Tino Asprilla');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('35','6','Prados del','1','Apto en prados del norte','Lujoso apto en cucuta barrio prados del norte',4,'Cra 20 nro 29',25000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/386-6396/386-6396_1_p.jpg','Laura Bolaños');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('36','6','Los patios','1','Los patios apto','Amplio apto en los patios',3,'Cra 60 nro 21',18000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/386-8129/386-8129_20_p.jpg','Juan Diego Gil');
