/*
-- Query: SELECT * FROM innodb.PROPIEDAD WHERE idCiudad = 5 OR idCiudad=6 OR idCiudad= 7
LIMIT 0, 1000


*/
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('19','5','Manga','1','Apartamento juan','Gran espacio para pasar el tiempo en cartagena.',3.5,'Cra 8 nro 1',25000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/581-2819/581-2819_1_p.jpg','Juan Esteban Osorio');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('20','5','Boca Grand','1','Apartamento en Boca Grande','Mejor estadia en Cartagena de Indias.',4,'Cra 9 nro 2',65000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/3967-1019051/3967-1019051_20_p.jpg','Pablo Martinez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('21','5','Pie de la','1','Apartamento pie de popa','Noches innolvidables en esta propiedad.',5,'Cra 80 nro 13',57000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/2398-21929/2398-21929_1_p.jpg','Camilo Serna');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('22','5','Marbella','1','Apartamento en Marbella','Gran apartamento en marbella',4,'Cra 9 nro 29',45000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/3967-2474895/3967-2474895_1_p.jpg','Alma Marcela Lopez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('23','5','Castillogr','1','Apartamento de Castillogrande','Ubicado en uno de los mejores barrios de la heroica.',3,'Cra 2 nro 02',87000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/2398-21780/2398-21780_1_p.jpg','Larry Dominguez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('24','5','Manga','1','Manga apartament','Grandes espacios en este apartamento',5,'Cra 5 nro 1',32000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/3967-1984797/3967-1984797_1_p.jpg','Esteban Galindo');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('25','7','Costa herm','1','Casa en Costa hermosa','Gran comodidad en costa hermosa soledad',4,'Calle 2 nro 2',82000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/130-3323/130-3323_1_p.jpg','Daniel Rios');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('26','7','Hipodromo','1','apto en Hipodromo','El mejor lugar para estar en soledad',4.5,'Calle 29 nro 29',45000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/671-70177/671-70177_19_p.jpg','Juan Camilo Gil');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('27','7','Las trinit','1','Apto en Las trinitarias','Apto con grandes espacios para vivir tranquilo',5,'Calle 2 nro 7',56000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/5410-9898/5410-9898_1_p.jpg','Hermen Taborda');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('28','7','Trinitaria','1','Apartamento en Trinitarias','Ubicado en el mejor sector de soledad',4,'Calle 24 nro 1',15000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/671-70188/671-70188_21_p.jpg','Sebastian Lopoldo');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('29','7','Villa kata','1','Apto En villa katanga','Mejor estadia en villa katanga',3.5,'Calle 20 nro 29',45000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/671-74199/671-74199_9_p.jpg','Pedro Pablo L');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('30','7','El parque','1','Apto en Parque','Gran apto ubicado en el barrio Parque',4,'Calle 5 nro 29',100000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/130-2777/130-2777_21_p.jpg','Luis Fernanda W');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('31','6','Avenida de','1','Apto en renta avenida del rio','Gran apartamento en zona residencial cucuta',4,'Cra 20 nro 2',45000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/386-2745/386-2745_18_p.jpg','Roberto Florez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('32','6','Blanco','1','Apto en Blanco','Una de las mejores ubicaciones en cucuta',3.5,'Cra 21 nro 28',29000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/386-2051/386-2051_1_p.jpg','Aldrin Alexander R');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('33','6','Prados del','1','Apartamento en prados del norte','Gran lugar para pasar estadia en cucuta',4,'Cra 30 nro 11',32000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/386-8119/386-8119_1_p.jpg','Pacho Maturana');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('34','6','Villa del','1','Apto en villa del rosario','Ubicado en una buena zona residencial',4.5,'Cra 27 nro 43',50000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/386-8193/386-8193_1_p.jpg','Tino Asprilla');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('35','6','Prados del','1','Apto en prados del norte','Lujoso apto en cucuta barrio prados del norte',4,'Cra 20 nro 29',25000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/386-6396/386-6396_1_p.jpg','Laura Bolaños');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('36','6','Los patios','1','Los patios apto','Amplio apto en los patios',3,'Cra 60 nro 21',18000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/386-8129/386-8129_20_p.jpg','Juan Diego Gil');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('37','3','Salomia','1','Carmen','Apartamento totalmente amoblado, buenas vistas',4.4,'Crr 30 # 60-75',80000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/11031-M2621264/11031-M2621264_1_h.jpg','Cecilia Ortega');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('38','3','Valle del Lili','1','Apt ceci','Arriendo alquiler apartamento amoblado. Diseño exclusivo con todo nuevo, excelente distribución, 55',4.5,'Cll 15 #18-02',100000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/9947-10405316/9947-10405316_1_h.jpg','Claudia Patricia');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('39','3','Flora','1','Edf Claudia','Apto tercer piso, amplio, salacomedor',4,'Crra 30 #54-25',70000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/3964-M2604798/3964-M2604798_1_h.jpg','Claudia Patricia');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('40','8','Belen','1','Apt Belen','Lindo apartamento para estrenar, amplios espacios, vista panoramica, sector tranquilo, excelente pre',4.9,'Crra 15 #80-10',150000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/426-M2225830/426-M2225830_2_h.jpg','Daison Teose');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('41','4','Prado','1','Boston','Apartamento amplio fresco buenos acabados buena distribución',4.6,'Cll 45 #48-78',120000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/671-81965/671-81965_13_h.jpg','Felipe Diaz');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('42','3','Cristales','1','Zeal','76 metros cuadrados, sala comedor, balcón, alcoba principal con baño y vestier',4.3,'Crra 75 #12-53',140000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/548-216/548-216_128_h.jpg','Gabriela Molina');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('43','3','Normandia','1','Kennedy','7Espectacular apartamento con espacios confortables en el oeste de cali',4.7,'Cll 52 #15-63',65000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/5423-M2289983/5423-M2289983_22_h.jpg','Henry Strak');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('44','3','Peñon','1','Alfa','Tiene sala, baño social, comedor, balcón grande con vista panorámica. Zona de estar. Estudio',3.9,'Crr 82 #32-9',50000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/5423-M2289983/5423-M2289983_22_h.jpg','David Perez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('45','3','Centenario','1','Thureil','Arriendo apartamento en 3er piso, ubicado cerca a centros comerciales, clínicas y bancos, fáciles ví',4.6,'Crr 72 #35-17',120000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/9947-10405327/9947-10405327_3_h.jpg','Angela Gutierrez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('46','3','Versalles','1','San Jose','Apartamento en quinto piso, amplio a una cuadra de la torre de cali',4.6,'Cll 15 #18-03',120000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/3964-M2606494/3964-M2606494_12_h.jpg','Jorge Velez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('47','4','Santana','1','Brizzie','Arriendo de apartamento en barranquilla para estrenar, con administración incluida',4.6,'Cll 45 #48-78',100000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/7515-803572/7515-803572_42_h.jpg','Daniel Martinez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('48','4','Miramar','1','Esperanza','Arriendo apartamento totalmente amoblado, con administración incluida,',4.6,'Crr 17 # 22-05',140000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/7515-554943/7515-554943_21_h.jpg','Carmen Diaz');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('49','4','Mercedes','1','Beta','Apartamento para arriendo amplio fresco acogedor cerca a transporte publico',4.2,'Crr 72 # 30-52',70000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/671-81967/671-81967_1_h.jpg','Luis Cebada');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('50','4','Tabor','1','Xerlox','Arriendo espectacular apartaestudio al norte de la ciudad',4.9,'Crr 43 # 10-22',110000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/2361-88357/2361-88357_6_h.jpg','Hugo Diaz');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('51','4','Palmas','1','Ani','Cuenta con piso de cerámica y cielo raso en drywall',4.4,'Cll 32 # 67-10',80000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/2398-21605/2398-21605_12_h.jpg','Ines Gonzales');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('52','8','Vergel','1','Sacro','Hermoso apartamento para la arriendo con vista panorámica',4.3,'Cll 22 # 12-30',130000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/661-M2607140/661-M2607140_7_h.jpg','Alejandro Saez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('53','8','Picaleña','1','Zary','Buenas vías de acceso , amplio , iluminado, zona muy tranquila',4,'Cll 32 # 55-80',80000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/1265-2364880/1265-2364880_58_h.jpg','Daniel Ramirez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('54','8','Santa Ana','1','Casa Rodriguez','Zonas sociales terminadas y en funcionamiento, cómodas vías de acceso',3.7,'Crra 52 #32-80',60000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/661-M2412472/661-M2412472_5_h.jpg','Sara Rodriguez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('55','8','Valparaiso','1','Rosario','Hermoso apartamento para arrendar en sector residencial y comercial, cerca a almacén éxito',3.6,'Crra 15 #40-17',90000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/661-M2605992/661-M2605992_32_h.jpg','Rodrigo Perez');
INSERT INTO `` (`idPropiedad`,`idCiudad`,`barrio`,`idAgencia`,`nombrePropiedad`,`descripcion`,`ratingPropiedad`,`direccion`,`precioNoche`,`currency`,`urlMiniatura`,`propietario`) VALUES ('56','8','Varsovia','1','Helen','Hermoso apartamento de 80 mts2, cocina integral a gas, muebles superiores e inferiores',4.4,'Cll 33 # 18-07',110000,'COP','https://metrocuadrado.blob.core.windows.net/inmuebles/661-M2605972/661-M2605972_1_h.jpg','Helen Herran');

